version: '3.9'
services:
  deep-face-webpi:
    image: deep-face-webpi
    ports:
      - 8000:8000

    networks:
      - genocs
    # network_mode: host
    volumes:
      - deep-face:/root

networks:
  genocs:
    name: genocs-network
    external: true

volumes:
  deep-face:
    driver: local